Repository digdir/digdir-camp-2025-desKI-frontend, pull requests merged in 2025-07, with the labels that each got.

#25 Feat: Create a page for the chatbot
  Dockerfile
  design-tokens-build/colors.d.ts
  design-tokens-build/deski.css
  design-tokens/$designsystemet.json
  design-tokens/$metadata.json
  design-tokens/$themes.json
  design-tokens/primitives/globals.json
  design-tokens/primitives/modes/color-scheme/dark/deski.json
  design-tokens/primitives/modes/color-scheme/dark/global.json
  design-tokens/primitives/modes/color-scheme/light/deski.json
  design-tokens/primitives/modes/color-scheme/light/global.json
  design-tokens/primitives/modes/size/global.json
  design-tokens/primitives/modes/size/large.json
  design-tokens/primitives/modes/size/medium.json
  design-tokens/primitives/modes/size/small.json
  design-tokens/primitives/modes/typography/primary/deski.json
  design-tokens/primitives/modes/typography/secondary/deski.json
  design-tokens/primitives/modes/typography/size/large.json
  design-tokens/primitives/modes/typography/size/medium.json
  design-tokens/primitives/modes/typography/size/small.json
  design-tokens/semantic/color.json
  design-tokens/semantic/modes/main-color/accent.json
  design-tokens/semantic/modes/support-color/brand1.json
  design-tokens/semantic/modes/support-color/brand2.json
  design-tokens/semantic/modes/support-color/brand3.json
  design-tokens/semantic/style.json
  design-tokens/themes/deski.json
  docker-compose.yml
  index.html
  nginx.conf
  package-lock.json
  package.json
  public/logo.svg
  public/vite.svg
  src/App.tsx
  src/Pages/ChatbotPage/ChatbotPage.module.css
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/Pages/ChatbotPage/index.ts
  src/Pages/StartPage/StartPage.module.css
  src/Pages/StartPage/StartPage.tsx
  src/assets/react.svg
  src/components/ChatBubble/ChatBubble.module.css
  src/components/ChatBubble/ChatBubble.tsx
  src/components/ChatLoader/ChatLoader.module.css
  src/components/ChatLoader/ChatLoader.tsx
  src/components/Chats/Chats.tsx
  src/data/solutions.ts
  src/styles/common.css
Labels: feature

#37 Feature: create dark mode functionality
  src/App.tsx
  src/Pages/ChatbotPage/ChatbotPage.module.css
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/Pages/StartPage/StartPage.module.css
  src/Pages/StartPage/StartPage.tsx
  src/assets/index.ts
  src/components/ChatBubble/ChatBubble.module.css
  src/components/Layout/Layout.tsx
  src/components/Logo/Logo.tsx
  src/components/UtilityBar/ColorModeSwitch/ColorModeSwitch.tsx
  src/components/UtilityBar/UtilityBar.tsx
  src/components/router/router.tsx
  src/lib/settings.ts
  src/main.tsx
  src/root.tsx
  src/routes/settings.tsx
  src/styles/common.css
Labels: design

#38 Feature: create language functionality
  package-lock.json
  package.json
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/Pages/StartPage/StartPage.tsx
  src/components/UtilityBar/LanguageDropdown/LanguageDropdown.tsx
  src/components/UtilityBar/UtilityBar.tsx
  src/data/solutions.ts
  src/i18n/constants.ts
  src/i18n/i18n.ts
  src/i18n/translations.ts
  src/i18n/types.ts
Labels: feature

#42 Feature: add tooltips
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/components/CameraButton/CameraButton.tsx
  src/components/UtilityBar/ColorModeSwitch/ColorModeSwitch.tsx
  src/components/UtilityBar/LanguageDropdown/LanguageDropdown.tsx
  src/i18n/constants.ts
  src/i18n/translations.ts
Labels: feature

#47 Feat: Connect to backend api
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/api/chatApi.ts
  src/i18n/constants.ts
  src/i18n/translations.ts
Labels: feature

#51 Enhancement: differentiate brukerstotte and servicedesk
  README.md
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/Pages/StartPage/StartPage.tsx
  src/main.tsx
  src/router/router.tsx
Labels: enhancement, refactor

#53 52 feature send chat history to backend
  package-lock.json
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/api/chatApi.ts
Labels: feature

#54 Enhancement: Make the dropdown menu work
  package-lock.json
  package.json
  src/Pages/ChatbotPage/ChatbotPage.module.css
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/Pages/StartPage/StartPage.tsx
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/DropdownMenu/DropdownMenu.tsx
  src/data/solutions.ts
  src/router/router.tsx
  src/utils/slugify.ts
Labels: enhancement, refactor

#58 feat: switch between brukerstotte and servicedesk endpoint
  src/Pages/ChatbotPage/ChatbotPage.tsx
  src/api/chatApi.ts
Labels: enhancement
